using AegisEInvoicing.Application.Features.InvoiceManagement.Commands.CreateFIRSInvoice;
using AegisEInvoicing.FIRSAccessPoint.Models.Enumerators;
using System.ComponentModel.DataAnnotations;

namespace AegisEInvoicing.ERP.API.Models;

/// <summary>
/// Request model for creating a new FIRS-compliant invoice
/// </summary>
public class CreateInvoiceRequest
{
    /// <summary>
    /// Business ID that the invoice belongs to
    /// </summary>
    /// <example>e3b0c442-98fc-4629-9c9f-1a54a8d0e23f</example>
    [Required(ErrorMessage = "Aegis Business ID is required")]
    public Guid AegisBusinessId { get; init; }

    /// <summary>
    /// Invoice Number (from ERP or generated by the system if omitted)
    /// </summary>
    /// <example>INV-2025-00045</example>
    public string? InvoiceNumber { get; init; }

    /// <summary>
    /// Invoice issue date (YYYY-MM-DD)
    /// </summary>
    /// <example>2025-03-10</example>
    [Required(ErrorMessage = "Issue date is required")]
    public DateOnly IssueDate { get; init; }

    /// <summary>
    /// Invoice due date (must be after issue date)
    /// </summary>
    /// <example>2025-04-10</example>
    public DateOnly? DueDate { get; init; }

    /// <summary>
    /// Invoice issue time (HH:mm:ss)
    /// </summary>
    /// <example>09:15:00</example>
    public TimeOnly? IssueTime { get; set; }

    /// <summary>
    /// Invoice type information
    /// </summary>
    /// <example>
    /// {
    ///   "name": "Standard Invoice",
    ///   "code": 380
    /// }
    /// </example>
    [Required(ErrorMessage = "Invoice type is required")]
    public InvoiceTypeRequest InvoiceType { get; init; } = null!;

    /// <summary>
    /// Invoice kind (B2B, B2C, B2G) - Optional
    /// </summary>
    /// <example>B2B</example>
    public string? InvoiceKind { get; init; }

    /// <summary>
    /// Currency information
    /// </summary>
    /// <example>
    /// {
    ///   "name": "Nigerian Naira",
    ///   "code": "NGN"
    /// }
    /// </example>
    [Required(ErrorMessage = "Currency is required")]
    public CurrencyRequest Currency { get; init; } = null!;

    /// <summary>
    /// Delivery period information
    /// </summary>
    /// <example>
    /// {
    ///   "startDate": "2025-03-01",
    ///   "endDate": "2025-03-31"
    /// }
    /// </example>
    [Required(ErrorMessage = "Delivery period is required")]
    public DeliveryPeriodRequest DeliveryPeriod { get; init; } = null!;

    /// <summary>
    /// Payment means (code and name)
    /// </summary>
    /// <example>
    /// {
    ///   "code": "30",
    ///   "name": "Bank Transfer"
    /// }
    /// </example>
    [Required(ErrorMessage = "Payment means is required")]
    public PaymentMeansRequest PaymentMeans { get; init; } = null!;

    /// <summary>
    /// Additional notes or comments
    /// </summary>
    /// <example>Payment expected within 30 days from invoice date</example>
    [StringLength(1000, ErrorMessage = "Note cannot exceed 1000 characters")]
    public string? Note { get; init; }

    /// <summary>
    /// Payment reference number
    /// </summary>
    /// <example>REF-TRX-2025-001</example>
    [StringLength(100, ErrorMessage = "Payment reference cannot exceed 100 characters")]
    public string? PaymentReference { get; init; }

    /// <summary>
    /// Payment terms
    /// </summary>
    /// <example>Net 30 days</example>
    [StringLength(500, ErrorMessage = "Payment terms cannot exceed 500 characters")]
    public string? PaymentTerms { get; init; }

    /// <summary>
    /// Customer or supplier information
    /// </summary>
    /// <example>
    /// {
    ///   "name": "ABC Manufacturing Ltd.",
    ///   "description": "Registered supplier of industrial electrical materials and installation services",
    ///   "phone": "+2348012345678",
    ///   "email": "finance@abcmfg.com",
    ///   "taxIdentificationNumber": "12345678-0001",
    ///   "address": {
    ///     "street": "15 Industrial Layout",
    ///     "city": "Ikeja",
    ///     "state": "Lagos",
    ///     "country": "NG",
    ///     "postalCode": "100271"
    ///   }
    /// }
    /// </example>
    [Required(ErrorMessage = "Party information is required")]
    public PartyRequest Party { get; init; } = null!;

    /// <summary>
    /// List of invoice items (at least one required)
    /// </summary>
    /// <example>
    /// [
    ///   {
    ///     "name": "Electrical Cable (100m Roll)",
    ///     "itemDescription": "High-voltage copper electrical cable suitable for industrial power installations",
    ///     "itemCategory": "Electrical Materials",
    ///     "serviceCode": { "code": "E1234", "name": "Electrical Installation Service" },
    ///     "taxCategory": { "name": "STANDARD_VAT", "percent": 7.5 },
    ///     "unitPrice": 2500.0,
    ///     "quantity": 100,
    ///     "discountFee": { "amount": 10, "code": "Percent" },
    ///     "additionalFee": { "amount": 2000.0, "code": "NGN" }
    ///   },
    ///   {
    ///     "name": "Installation Service",
    ///     "itemDescription": "On-site installation and testing of supplied electrical materials",
    ///     "itemCategory": "Services",
    ///     "serviceCode": { "code": "S9010", "name": "On-site Installation" },
    ///     "taxCategory": { "name": "STANDARD_VAT", "percent": 7.5 },
    ///     "unitPrice": 50000.0,
    ///     "quantity": 1,
    ///     "discountFee": { "amount": 5, "code": "Percent" },
    ///     "additionalFee": { "amount": 0.0, "code": "NGN" }
    ///   }
    /// ]
    /// </example>
    [Required(ErrorMessage = "Invoice items are required")]
    [MinLength(1, ErrorMessage = "At least one invoice item is required")]
    public List<CreateInvoiceItemDto> InvoiceItems { get; init; } = [];

    /// <summary>
    /// Billing References are optional
    /// </summary>
    /// <example>
    ///  "billingReferences":
    ///  [
    ///     {
    ///        "irn": "ITW001-E9E0C0D3-20240619",
    ///        "issueDate":"2024-05-14"
    ///     },
    ///     {
    ///        "irn": "ITW001-E9E0C0D3-20240619",
    ///        "issueDate":"2024-05-14"
    ///     } //optional - second value to ...x in array is always optional
    /// ]
    /// </example>
    public List<BillingReferenceRequest>? BillingReferences { get; init; }

    /// <summary>
    /// Optional reference to dispatch/shipping document
    /// </summary>
    /// <example>
    /// {
    ///   "irn": "ITW00000001-E9E0C0D3-20240619",
    ///   "issueDate": "2024-06-19"
    /// }
    /// </example>
    public DocumentReferenceRequest? DispatchDocumentReference { get; init; }

    /// <summary>
    /// Optional reference to receipt/acknowledgment document
    /// </summary>
    /// <example>
    /// {
    ///   "irn": "ITW00000002-E9E0C0D3-20240620",
    ///   "issueDate": "2024-06-20"
    /// }
    /// </example>
    public DocumentReferenceRequest? ReceiptDocumentReference { get; init; }

    /// <summary>
    /// Optional reference to originator/source document
    /// </summary>
    /// <example>
    /// {
    ///   "irn": "ITW00000003-E9E0C0D3-20240621",
    ///   "issueDate": "2024-06-21"
    /// }
    /// </example>
    public DocumentReferenceRequest? OriginatorDocumentReference { get; init; }

    /// <summary>
    /// Optional reference to contract/agreement document
    /// </summary>
    /// <example>
    /// {
    ///   "irn": "ITW00000004-E9E0C0D3-20240622",
    ///   "issueDate": "2024-06-22"
    /// }
    /// </example>
    public DocumentReferenceRequest? ContractDocumentReference { get; init; }

    /// <summary>
    /// Optional list of additional supporting document references
    /// </summary>
    /// <example>
    /// [
    ///   {
    ///     "irn": "ITW00000005-E9E0C0D3-20240623",
    ///     "issueDate": "2024-06-23"
    ///   },
    ///   {
    ///     "irn": "ITW00000006-E9E0C0D3-20240624",
    ///     "issueDate": "2024-06-24"
    ///   }
    /// ]
    /// </example>
    public List<DocumentReferenceRequest>? AdditionalDocumentReferences { get; init; }
}

/// <summary>
/// Invoice type request model
/// </summary>
public class InvoiceTypeRequest
{
    /// <summary>
    /// Invoice type name
    /// </summary>
    /// <example>Standard Invoice</example>
    public string Name { get; init; } = null!;

    /// <summary>
    /// FIRS invoice type code
    /// </summary>
    /// <example>380</example>
    public int Code { get; init; }
}

/// <summary>
/// Currency request model
/// </summary>
public class CurrencyRequest
{
    /// <summary>
    /// Currency name
    /// </summary>
    /// <example>Nigerian Naira</example>
    public string Name { get; init; } = null!;

    /// <summary>
    /// ISO 4217 currency code
    /// </summary>
    /// <example>NGN</example>
    public string Code { get; init; } = null!;
}

/// <summary>
/// Delivery period request model
/// </summary>
public class DeliveryPeriodRequest
{
    /// <summary>
    /// Delivery start date
    /// </summary>
    /// <example>2025-03-01</example>
    public DateOnly StartDate { get; init; }

    /// <summary>
    /// Delivery end date
    /// </summary>
    /// <example>2025-03-31</example>
    public DateOnly EndDate { get; init; }
}

/// <summary>
/// Payment means request model
/// </summary>
public class PaymentMeansRequest
{
    /// <summary>
    /// Payment means code (e.g., 30 for Credit Transfer, 10 for Cash)
    /// </summary>
    /// <example>30</example>
    public string Code { get; init; } = null!;

    /// <summary>
    /// Payment means name
    /// </summary>
    /// <example>Bank Transfer</example>
    public string Name { get; init; } = null!;
}

/// <summary>
/// Request model for updating invoice payment status
/// </summary>
/// <param name="PaymentStatus">New payment status for the invoice</param>
/// <param name="Reference">Optional payment reference</param>
public record UpdateInvoicePaymentStatusRequest(
    [Required(ErrorMessage = "Payment status is required")]
    PaymentStatus PaymentStatus,
    string? Reference,
    decimal? Amount
);
