using AegisEInvoicing.Domain.Common.Implementation;

namespace AegisEInvoicing.Domain.Entities;

/// <summary>
/// Subscription key generated by KMPG for on-premise deployments
/// </summary>
public class SubscriptionKey : AuditableAggregateRoot
{
    public string Key { get; private set; } = default!;
    public string BusinessName { get; private set; } = default!;
    public string ContactEmail { get; private set; } = default!;
    public string? ContactPhone { get; private set; }
    public DateTimeOffset ExpiryDate { get; private set; }
    public bool IsActive { get; private set; }
    public bool IsUsed { get; private set; }
    public DateTimeOffset? UsedAt { get; private set; }
    public Guid? UsedBy { get; private set; }
    public string? UsageNotes { get; private set; }
    public int MaxUsers { get; private set; }
    public int MaxBusinesses { get; private set; }
    public string? Features { get; private set; }

    // Parameterless constructor for Entity Framework
    private SubscriptionKey()
    {
        IsActive = true;
        IsUsed = false;
        MaxUsers = 10; // Default
        MaxBusinesses = 1; // Default for on-premise
    }

    public static SubscriptionKey Create(
        string businessName,
        string contactEmail,
        string? contactPhone,
        DateTimeOffset expiryDate,
        int maxUsers,
        int maxBusinesses,
        string? features,
        Guid createdBy)
    {
        var subscriptionKey = new SubscriptionKey
        {
            Id = Guid.CreateVersion7(),
            Key = GenerateSubscriptionKey(),
            BusinessName = businessName,
            ContactEmail = contactEmail,
            ContactPhone = contactPhone,
            ExpiryDate = expiryDate,
            MaxUsers = maxUsers,
            MaxBusinesses = maxBusinesses,
            Features = features,
            CreatedAt = DateTimeOffset.UtcNow,
            CreatedBy = createdBy
        };

        return subscriptionKey;
    }

    public void MarkAsUsed(Guid usedBy, string? notes = null)
    {
        if (IsUsed)
            throw new InvalidOperationException("Subscription key has already been used");

        if (!IsActive)
            throw new InvalidOperationException("Subscription key is not active");

        if (ExpiryDate < DateTimeOffset.UtcNow)
            throw new InvalidOperationException("Subscription key has expired");

        IsUsed = true;
        UsedAt = DateTimeOffset.UtcNow;
        UsedBy = usedBy;
        UsageNotes = notes;
        UpdatedAt = DateTimeOffset.UtcNow;
        UpdatedBy = usedBy;
    }

    public void Deactivate(Guid deactivatedBy, string? reason = null)
    {
        IsActive = false;
        UpdatedAt = DateTimeOffset.UtcNow;
        UpdatedBy = deactivatedBy;
        UsageNotes = reason;
    }

    public void Reactivate(Guid reactivatedBy)
    {
        if (IsUsed)
            throw new InvalidOperationException("Cannot reactivate a used subscription key");

        if (ExpiryDate < DateTimeOffset.UtcNow)
            throw new InvalidOperationException("Cannot reactivate an expired subscription key");

        IsActive = true;
        UpdatedAt = DateTimeOffset.UtcNow;
        UpdatedBy = reactivatedBy;
    }

    public bool IsValid()
    {
        return IsActive && !IsUsed && ExpiryDate > DateTimeOffset.UtcNow;
    }

    private static string GenerateSubscriptionKey()
    {
        // Generate a secure, unique subscription key
        // Format: KMPG-{8 chars}-{8 chars}-{8 chars}
        var random = new Random();
        const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        
        var part1 = new string(Enumerable.Repeat(chars, 8).Select(s => s[random.Next(s.Length)]).ToArray());
        var part2 = new string(Enumerable.Repeat(chars, 8).Select(s => s[random.Next(s.Length)]).ToArray());
        var part3 = new string(Enumerable.Repeat(chars, 8).Select(s => s[random.Next(s.Length)]).ToArray());
        
        return $"KMPG-{part1}-{part2}-{part3}";
    }
}